crud/urls.py
from django.urls import path

from . import views

app_name = 'view'
urlpatterns = [
    path('', views.CreateListTodo.as_view(), name='list_view'),
    path('edit_todo/<int:pk>', views.UpdateTodo.as_view(), name='edit_todo'),
    path('delete_todo/<int:pk>', views.DeleteTodo.as_view(), name='delete_todo'),
]

todo_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from crud import viewsets

router = routers.DefaultRouter()
router.register(r'todo', viewsets.TodoViewset)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('view/', include('crud.urls')),
    path('api/v1/', include(router.urls)),
]

crud/models.py
from django.utils import timezone
from django.db import models


class Todo(models.Model):

    created_at = models.DateTimeField(default=timezone.now)
    state = models.CharField(
        max_length=2,
        choices=(('TD', 'todo'), ('IP', 'in-progress'), ('DN', 'done')),
        default='TD',
    )
    due_at = models.DateTimeField(null=True, blank=True)
    text = models.TextField()

    def __str__(self):
        return "{}:{}".format(self.get_state_display(), self.text[0:20])

crud/forms.py
from datetime import datetime
import calendar

from django.forms import ModelForm, widgets, Textarea
from crud.models import Todo

from django.utils import dates as dj_dates


class DateTimeWidget(widgets.MultiWidget):
    """A Date time widgit for year, month, day, hour, minute(15 min intervals).

    Uses a set of 5 Select widgits, one for each range.
    """
    def __init__(self, attrs=None):
        now_year = datetime.now().year
        years = [(year, year) for year in range(now_year, now_year + 5)]
        months = dj_dates.MONTHS_AP.items()
        days = [(i, i) for i in range(1, 32)]
        hours = [(i, i) for i in range(0, 24)]
        minutes = [(i, i) for i in (0, 15, 30, 45)]
        _widgets = (
            widgets.Select(attrs=attrs, choices=days),
            widgets.Select(attrs=attrs, choices=months),
            widgets.Select(attrs=attrs, choices=years),
            widgets.Select(attrs=attrs, choices=hours),
            widgets.Select(attrs=attrs, choices=minutes),
        )
        super().__init__(_widgets, attrs)

    def decompress(self, value):
        if value:
            return [value.day, value.month, value.year, value.hour, value.minute]
        return [None, None, None, None, None]

    def value_from_datadict(self, data, files, name):
        """Parses a valid datetime.  Sets default value to current datetime."""
        datelist = [
            widget.value_from_datadict(data, files, name + '_%s' % i)
            for i, widget in enumerate(self.widgets)]
        try:
            year = int(datelist[2])
            month = int(datelist[1])
            # Deals with day is out of range for month
            day = min(int(datelist[0]), calendar.monthrange(year, month)[1])
            dt = datetime(
                year=year,
                month=month,
                day=day,
                hour=int(datelist[3]),
                minute=int(datelist[4]),
            )
            return dt
        except TypeError:
            return datetime.now()


class TodoForm(ModelForm):
    class Meta:
        model = Todo

        fields = ['text', 'state', 'due_at']
        widgets = {
            'text': Textarea(attrs={'cols': 50, 'rows': 2}),
            'due_at': DateTimeWidget()
        }

crud/views.py
import datetime

from django.urls import reverse_lazy
from django.views import generic

from .models import Todo
from crud.forms import TodoForm


class CreateListTodo(generic.CreateView):
    """View for creating and listing todos."""
    template_name = 'crud/todo_list.html'
    form_class = TodoForm
    success_url = reverse_lazy('view:list_view')

    def get_initial(self):
        """The initial values for the create form."""
        now = datetime.datetime.now()
        # Round up minutes to next quarter hour
        init_dt = now + (datetime.datetime.min - now) % datetime.timedelta(minutes=15)
        return {
            'text': 'Whatcha gotta do?',
            'due_at': init_dt
        }

    def get_context_data(self, **kwargs):
        """Get the list of todos for the list view."""
        kwargs['todo_list'] = Todo.objects.order_by('-created_at').all()
        return super(CreateListTodo, self).get_context_data(**kwargs)


class UpdateTodo(generic.UpdateView):
    """Update an existing Todo entry using the create form."""
    template_name = 'crud/todo_form.html'
    form_class = TodoForm
    success_url = reverse_lazy('view:list_view')

    def get_queryset(self):
        """Fetch the correct item via primary key."""
        query_set = Todo.objects.filter(pk=self.kwargs['pk'])
        return query_set


class DeleteTodo(generic.DeleteView):
    """Delete an existing Todo entry."""
    model = Todo
    success_url = reverse_lazy('view:list_view')

crud/templates/crud/todo_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo confirm delete</title>
</head>
<body>
<h1>Todo Delete</h1>
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Yes" />
</form>
</body>
</html>

crud/templates/crud/todo_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo create form</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html>

crud/templates/crud/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo tracker Home</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.18/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.18/datatables.min.js"></script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'crud/style.css' %}">
    <script type="text/javascript" src="{% static 'crud/datatables.js' %}"></script>
</head>
<body>
    <form method="post">
        {% csrf_token %}

        <table id="datatables_table" class="display">
            <thead>
            <tr>
                <th></th>
                <th>State</th>
                <th>Due At</th>
                <th>Text</th>
                <th>Created At</th>
                <th></th>
            </tr>
            <tr id="create_header">
                <td></td>
                <td>{{ form.state }}</td>
                <td>{{ form.due_at }}</td>
                <td>{{ form.text }}</td>
                <td><input type="submit" value="Create"></td>
                <td></td>
            </tr>
            </thead>
            <tbody>
            {% for todo in todo_list %}
                <tr class="entry_{{ todo.state }}">
                    <td><a href="{% url "view:delete_todo" todo.id %}">Delete</a></td>
                    <td>{{ todo.get_state_display }}</td>
                    <td>{{ todo.due_at }}</td>
                    <td>{{ todo.text }}</td>
                    <td>{{ todo.created_at }}</td>
                    <td><a href="{% url "view:edit_todo" todo.id %}">Update</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </form>

</body>
</html>